openapi: 3.0.4
info:
  contact:
    email: support@apibricks.io
    name: API BRICKS LTD
    url: https://www.finfeedapi.com
  license:
    name: MIT License
    url: https://github.com/api-bricks/api-bricks-sdk/blob/master/LICENSE
  title: FinFeedAPI Currencies Realtime REST API
  version: v1
servers:
- url: https://api-realtime.fx.finfeedapi.com
security:
- APIKey: []
- JWT: []
tags:
- name: RateLimit
  x-displayName: RateLimit
- description: Exchange rate is defined as (VWAP-24H) last 24 hour (rolling window
    over time) Volume Weighted Average Price across multiple data sources listed on
    our platform. We are selecting and managing the data sources that are used in
    the calculation based on multiple factors to provide data of highest quality.
  name: Exchange Rates
  x-displayName: Exchange Rates
- description: Use these endpoints to discover supported assets and asset icons. This
    metadata helps you identify valid asset IDs before requesting exchange rates.
  name: Metadata
  x-displayName: Metadata
paths:
  /v1/exchangerate/{asset_id_base}/{asset_id_quote}:
    get:
      description: "Retrieves the exchange rate for a specific base and quote asset\
        \ at a given time or the current rate.\n            \n:::info\nIf you are\
        \ using an exchange rate for mission-critical operations, then for best reliability,\
        \ you should measure the difference between current time and the time returned\
        \ from the response to ensure that value of the difference between those meets\
        \ your internal requirements.\n:::"
      operationId: Get specific rate
      parameters:
      - description: Requested exchange rate base asset identifier (from the Metadata
          -> Assets)
        explode: false
        in: path
        name: asset_id_base
        required: true
        schema:
          type: string
        style: simple
      - description: Requested exchange rate quote asset identifier (from the Metadata
          -> Assets)
        explode: false
        in: path
        name: asset_id_quote
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              examples:
                Example response:
                  value:
                    time: 2026-08-04T06:07:30.6471332Z
                    asset_id_base: BTC
                    asset_id_quote: USD
                    rate: 10000.0
              schema:
                $ref: "#/components/schemas/v1.ExchangeRate"
            application/json:
              examples:
                Example response:
                  value:
                    time: 2026-08-04T06:07:30.6471332Z
                    asset_id_base: BTC
                    asset_id_quote: USD
                    rate: 10000.0
              schema:
                $ref: "#/components/schemas/v1.ExchangeRate"
            text/json:
              examples:
                Example response:
                  value:
                    time: 2026-08-04T06:07:30.6471332Z
                    asset_id_base: BTC
                    asset_id_quote: USD
                    rate: 10000.0
              schema:
                $ref: "#/components/schemas/v1.ExchangeRate"
            application/x-msgpack:
              examples:
                Example response:
                  value:
                    time: 2026-08-04T06:07:30.6471332Z
                    asset_id_base: BTC
                    asset_id_quote: USD
                    rate: 10000.0
              schema:
                $ref: "#/components/schemas/v1.ExchangeRate"
          description: successful operation
      summary: Get specific rate
      tags:
      - Exchange Rates
      x-accepts:
      - application/json
      - application/x-msgpack
      - text/json
      - text/plain
  /v1/exchangerate/{asset_id_base}:
    get:
      description: "Get the current exchange rate between requested asset and all\
        \ other assets.\n            \n:::info\nIf you are using an exchange rate\
        \ for mission-critical operations, then for best reliability, you should measure\
        \ the difference between current time and the time returned from the response\
        \ to ensure that value of the difference between those meets your internal\
        \ requirements.\n:::\n            \n:::info\nYou can invert the rates by using\
        \ Y = 1 / X equation, for example BTC/USD = 1 / (USD/BTC);\n:::"
      parameters:
      - description: Requested exchange rates base asset identifier (from the Metadata
          -> Assets)
        explode: false
        in: path
        name: asset_id_base
        required: true
        schema:
          type: string
        style: simple
      - description: Comma or semicolon delimited asset identifiers used to filter
          response (optional)
        explode: true
        in: query
        name: filter_asset_id
        required: false
        schema:
          type: string
        style: form
      - description: "True will invert all the rates (optional, if true then rates\
          \ will be calculated as `rate = 1 / actual_rate` eg. `USD/BTC` as `BTC/USD`)"
        explode: true
        in: query
        name: invert
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            text/plain:
              examples:
                Example response:
                  value:
                    asset_id_base: BTC
                    rates:
                    - time: 2017-08-09T14:31:37.0520000Z
                      asset_id_quote: USD
                      rate: 3258.887541779804
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: EUR
                      rate: 2782.5255080599272
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: CNY
                      rate: 21756.295595926054
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: GBP
                      rate: 2509.602420379958
              schema:
                $ref: "#/components/schemas/v1.ExchangeRates"
            application/json:
              examples:
                Example response:
                  value:
                    asset_id_base: BTC
                    rates:
                    - time: 2017-08-09T14:31:37.0520000Z
                      asset_id_quote: USD
                      rate: 3258.887541779804
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: EUR
                      rate: 2782.5255080599272
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: CNY
                      rate: 21756.295595926054
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: GBP
                      rate: 2509.602420379958
              schema:
                $ref: "#/components/schemas/v1.ExchangeRates"
            text/json:
              examples:
                Example response:
                  value:
                    asset_id_base: BTC
                    rates:
                    - time: 2017-08-09T14:31:37.0520000Z
                      asset_id_quote: USD
                      rate: 3258.887541779804
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: EUR
                      rate: 2782.5255080599272
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: CNY
                      rate: 21756.295595926054
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: GBP
                      rate: 2509.602420379958
              schema:
                $ref: "#/components/schemas/v1.ExchangeRates"
            application/x-msgpack:
              examples:
                Example response:
                  value:
                    asset_id_base: BTC
                    rates:
                    - time: 2017-08-09T14:31:37.0520000Z
                      asset_id_quote: USD
                      rate: 3258.887541779804
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: EUR
                      rate: 2782.5255080599272
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: CNY
                      rate: 21756.295595926054
                    - time: 2017-08-09T14:31:36.7570000Z
                      asset_id_quote: GBP
                      rate: 2509.602420379958
              schema:
                $ref: "#/components/schemas/v1.ExchangeRates"
          description: successful operation
      summary: Get all current rates
      tags:
      - Exchange Rates
      x-accepts:
      - application/json
      - application/x-msgpack
      - text/json
      - text/plain
  /v1/assets:
    get:
      description: "Retrieves all assets.\n            \n:::info\nOur asset identifiers\
        \ are aligned with the ISO 4217 currency codes standard only for fiat money\
        \ (government or law regulated currency).\n:::\n            \n:::info\nProperties\
        \ of the output are providing aggregated information from across all symbols\
        \ related to the specific asset. If you need to calculate your aggregation\
        \ (e.g., limiting only the particular type of symbols), you should use /v1/symbols\
        \ endpoint as a data source.\n:::"
      parameters:
      - description: "Comma or semicolon delimited asset identifiers used to filter\
          \ response. (optional, eg. `BTC;ETH`)."
        explode: true
        in: query
        name: filter_asset_id
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    name: Bitcoin
                    type_is_crypto: 1
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:55:07.6724523Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:17.8592413Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:11.8220000Z
                    data_symbols_count: 22711
                    volume_1hrs_usd: 1.0289443143649E11
                    volume_1day_usd: 2.08639232325616E12
                    volume_1mth_usd: 5.792916835998454E13
                    price_usd: 9166.207274778093
                    chain_addresses:
                    - chain_id: ARBITRUM
                      network_id: MAINNET
                      address: 0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
                    data_start: 2010-07-17
                    data_end: 2019-11-03
                  - asset_id: USD
                    name: US Dollar
                    type_is_crypto: 0
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:54:49.3807706Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:13.1863931Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:07.7870000Z
                    data_symbols_count: 10728
                    volume_1hrs_usd: 9.46645401652E9
                    volume_1day_usd: 2.2158075817349E11
                    volume_1mth_usd: 1.18166851746617E13
                    price_usd: 1.0
                    chain_addresses:
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0xd233d1f6fd11640081abb8db125f722b5dc729dc
                    data_start: 2010-07-17
                    data_end: 2019-11-03
              schema:
                items:
                  $ref: "#/components/schemas/v1.Asset"
                type: array
            application/json:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    name: Bitcoin
                    type_is_crypto: 1
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:55:07.6724523Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:17.8592413Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:11.8220000Z
                    data_symbols_count: 22711
                    volume_1hrs_usd: 1.0289443143649E11
                    volume_1day_usd: 2.08639232325616E12
                    volume_1mth_usd: 5.792916835998454E13
                    price_usd: 9166.207274778093
                    chain_addresses:
                    - chain_id: ARBITRUM
                      network_id: MAINNET
                      address: 0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
                    data_start: 2010-07-17
                    data_end: 2019-11-03
                  - asset_id: USD
                    name: US Dollar
                    type_is_crypto: 0
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:54:49.3807706Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:13.1863931Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:07.7870000Z
                    data_symbols_count: 10728
                    volume_1hrs_usd: 9.46645401652E9
                    volume_1day_usd: 2.2158075817349E11
                    volume_1mth_usd: 1.18166851746617E13
                    price_usd: 1.0
                    chain_addresses:
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0xd233d1f6fd11640081abb8db125f722b5dc729dc
                    data_start: 2010-07-17
                    data_end: 2019-11-03
              schema:
                items:
                  $ref: "#/components/schemas/v1.Asset"
                type: array
            text/json:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    name: Bitcoin
                    type_is_crypto: 1
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:55:07.6724523Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:17.8592413Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:11.8220000Z
                    data_symbols_count: 22711
                    volume_1hrs_usd: 1.0289443143649E11
                    volume_1day_usd: 2.08639232325616E12
                    volume_1mth_usd: 5.792916835998454E13
                    price_usd: 9166.207274778093
                    chain_addresses:
                    - chain_id: ARBITRUM
                      network_id: MAINNET
                      address: 0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
                    data_start: 2010-07-17
                    data_end: 2019-11-03
                  - asset_id: USD
                    name: US Dollar
                    type_is_crypto: 0
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:54:49.3807706Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:13.1863931Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:07.7870000Z
                    data_symbols_count: 10728
                    volume_1hrs_usd: 9.46645401652E9
                    volume_1day_usd: 2.2158075817349E11
                    volume_1mth_usd: 1.18166851746617E13
                    price_usd: 1.0
                    chain_addresses:
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0xd233d1f6fd11640081abb8db125f722b5dc729dc
                    data_start: 2010-07-17
                    data_end: 2019-11-03
              schema:
                items:
                  $ref: "#/components/schemas/v1.Asset"
                type: array
            application/x-msgpack:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    name: Bitcoin
                    type_is_crypto: 1
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:55:07.6724523Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:17.8592413Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:11.8220000Z
                    data_symbols_count: 22711
                    volume_1hrs_usd: 1.0289443143649E11
                    volume_1day_usd: 2.08639232325616E12
                    volume_1mth_usd: 5.792916835998454E13
                    price_usd: 9166.207274778093
                    chain_addresses:
                    - chain_id: ARBITRUM
                      network_id: MAINNET
                      address: 0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
                    data_start: 2010-07-17
                    data_end: 2019-11-03
                  - asset_id: USD
                    name: US Dollar
                    type_is_crypto: 0
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:54:49.3807706Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:13.1863931Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:07.7870000Z
                    data_symbols_count: 10728
                    volume_1hrs_usd: 9.46645401652E9
                    volume_1day_usd: 2.2158075817349E11
                    volume_1mth_usd: 1.18166851746617E13
                    price_usd: 1.0
                    chain_addresses:
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0xd233d1f6fd11640081abb8db125f722b5dc729dc
                    data_start: 2010-07-17
                    data_end: 2019-11-03
              schema:
                items:
                  $ref: "#/components/schemas/v1.Asset"
                type: array
          description: successful operation
      summary: List all assets
      tags:
      - Metadata
      x-accepts:
      - application/json
      - application/x-msgpack
      - text/json
      - text/plain
  /v1/assets/{asset_id}:
    get:
      parameters:
      - description: The asset ID.
        explode: false
        in: path
        name: asset_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    name: Bitcoin
                    type_is_crypto: 1
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:55:07.6724523Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:17.8592413Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:11.8220000Z
                    data_symbols_count: 22711
                    volume_1hrs_usd: 1.0289443143649E11
                    volume_1day_usd: 2.08639232325616E12
                    volume_1mth_usd: 5.792916835998454E13
                    price_usd: 9166.207274778093
                    chain_addresses:
                    - chain_id: ARBITRUM
                      network_id: MAINNET
                      address: 0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
                    data_start: 2010-07-17
                    data_end: 2019-11-03
                  - asset_id: USD
                    name: US Dollar
                    type_is_crypto: 0
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:54:49.3807706Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:13.1863931Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:07.7870000Z
                    data_symbols_count: 10728
                    volume_1hrs_usd: 9.46645401652E9
                    volume_1day_usd: 2.2158075817349E11
                    volume_1mth_usd: 1.18166851746617E13
                    price_usd: 1.0
                    chain_addresses:
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0xd233d1f6fd11640081abb8db125f722b5dc729dc
                    data_start: 2010-07-17
                    data_end: 2019-11-03
              schema:
                items:
                  $ref: "#/components/schemas/v1.Asset"
                type: array
            application/json:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    name: Bitcoin
                    type_is_crypto: 1
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:55:07.6724523Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:17.8592413Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:11.8220000Z
                    data_symbols_count: 22711
                    volume_1hrs_usd: 1.0289443143649E11
                    volume_1day_usd: 2.08639232325616E12
                    volume_1mth_usd: 5.792916835998454E13
                    price_usd: 9166.207274778093
                    chain_addresses:
                    - chain_id: ARBITRUM
                      network_id: MAINNET
                      address: 0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
                    data_start: 2010-07-17
                    data_end: 2019-11-03
                  - asset_id: USD
                    name: US Dollar
                    type_is_crypto: 0
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:54:49.3807706Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:13.1863931Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:07.7870000Z
                    data_symbols_count: 10728
                    volume_1hrs_usd: 9.46645401652E9
                    volume_1day_usd: 2.2158075817349E11
                    volume_1mth_usd: 1.18166851746617E13
                    price_usd: 1.0
                    chain_addresses:
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0xd233d1f6fd11640081abb8db125f722b5dc729dc
                    data_start: 2010-07-17
                    data_end: 2019-11-03
              schema:
                items:
                  $ref: "#/components/schemas/v1.Asset"
                type: array
            text/json:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    name: Bitcoin
                    type_is_crypto: 1
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:55:07.6724523Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:17.8592413Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:11.8220000Z
                    data_symbols_count: 22711
                    volume_1hrs_usd: 1.0289443143649E11
                    volume_1day_usd: 2.08639232325616E12
                    volume_1mth_usd: 5.792916835998454E13
                    price_usd: 9166.207274778093
                    chain_addresses:
                    - chain_id: ARBITRUM
                      network_id: MAINNET
                      address: 0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
                    data_start: 2010-07-17
                    data_end: 2019-11-03
                  - asset_id: USD
                    name: US Dollar
                    type_is_crypto: 0
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:54:49.3807706Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:13.1863931Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:07.7870000Z
                    data_symbols_count: 10728
                    volume_1hrs_usd: 9.46645401652E9
                    volume_1day_usd: 2.2158075817349E11
                    volume_1mth_usd: 1.18166851746617E13
                    price_usd: 1.0
                    chain_addresses:
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0xd233d1f6fd11640081abb8db125f722b5dc729dc
                    data_start: 2010-07-17
                    data_end: 2019-11-03
              schema:
                items:
                  $ref: "#/components/schemas/v1.Asset"
                type: array
            application/x-msgpack:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    name: Bitcoin
                    type_is_crypto: 1
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:55:07.6724523Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:17.8592413Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:11.8220000Z
                    data_symbols_count: 22711
                    volume_1hrs_usd: 1.0289443143649E11
                    volume_1day_usd: 2.08639232325616E12
                    volume_1mth_usd: 5.792916835998454E13
                    price_usd: 9166.207274778093
                    chain_addresses:
                    - chain_id: ARBITRUM
                      network_id: MAINNET
                      address: 0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
                    data_start: 2010-07-17
                    data_end: 2019-11-03
                  - asset_id: USD
                    name: US Dollar
                    type_is_crypto: 0
                    data_quote_start: 2014-02-24T17:43:05.0000000Z
                    data_quote_end: 2019-11-03T17:54:49.3807706Z
                    data_orderbook_start: 2014-02-24T17:43:05.0000000Z
                    data_orderbook_end: 2019-11-03T17:55:13.1863931Z
                    data_trade_start: 2010-07-17T23:09:17.0000000Z
                    data_trade_end: 2019-11-03T17:55:07.7870000Z
                    data_symbols_count: 10728
                    volume_1hrs_usd: 9.46645401652E9
                    volume_1day_usd: 2.2158075817349E11
                    volume_1mth_usd: 1.18166851746617E13
                    price_usd: 1.0
                    chain_addresses:
                    - chain_id: ETHEREUM
                      network_id: MAINNET
                      address: 0xd233d1f6fd11640081abb8db125f722b5dc729dc
                    data_start: 2010-07-17
                    data_end: 2019-11-03
              schema:
                items:
                  $ref: "#/components/schemas/v1.Asset"
                type: array
          description: successful operation
      summary: List all assets by asset ID
      tags:
      - Metadata
      x-accepts:
      - application/json
      - application/x-msgpack
      - text/json
      - text/plain
  /v1/assets/icons/{size}:
    get:
      description: Gets the list of icons (of the given size) for all the assets.
      parameters:
      - description: The size of the icons.
        explode: false
        in: path
        name: size
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            text/plain:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/f231d7382689406f9a50dde841418c64.png
                  - asset_id: ETH
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/04836ff3bc4d4d95820e0155594dca86.png
                  - asset_id: USD
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/4873707f25fe4de3b4bca6fa5c631011.png
              schema:
                items:
                  $ref: "#/components/schemas/v1.Icon"
                type: array
            application/json:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/f231d7382689406f9a50dde841418c64.png
                  - asset_id: ETH
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/04836ff3bc4d4d95820e0155594dca86.png
                  - asset_id: USD
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/4873707f25fe4de3b4bca6fa5c631011.png
              schema:
                items:
                  $ref: "#/components/schemas/v1.Icon"
                type: array
            text/json:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/f231d7382689406f9a50dde841418c64.png
                  - asset_id: ETH
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/04836ff3bc4d4d95820e0155594dca86.png
                  - asset_id: USD
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/4873707f25fe4de3b4bca6fa5c631011.png
              schema:
                items:
                  $ref: "#/components/schemas/v1.Icon"
                type: array
            application/x-msgpack:
              examples:
                Example response:
                  value:
                  - asset_id: BTC
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/f231d7382689406f9a50dde841418c64.png
                  - asset_id: ETH
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/04836ff3bc4d4d95820e0155594dca86.png
                  - asset_id: USD
                    url: https://s3.eu-central-1.amazonaws.com/bbxt-static-icons/type-id/png_16/4873707f25fe4de3b4bca6fa5c631011.png
              schema:
                items:
                  $ref: "#/components/schemas/v1.Icon"
                type: array
          description: successful operation
      summary: List all asset icons
      tags:
      - Metadata
      x-accepts:
      - application/json
      - application/x-msgpack
      - text/json
      - text/plain
  /internal/ratelimit/wsreq/ip:
    get:
      responses:
        "200":
          description: OK
      tags:
      - RateLimit
      x-accepts:
      - application/json
  /internal/ratelimit/wshello/ip:
    get:
      responses:
        "200":
          description: OK
      tags:
      - RateLimit
      x-accepts:
      - application/json
  /internal/ratelimit/wsconcon/apikey:
    get:
      responses:
        "200":
          description: OK
      tags:
      - RateLimit
      x-accepts:
      - application/json
components:
  schemas:
    v1.Asset:
      additionalProperties: false
      description: Represents an asset.
      example:
        asset_id: asset_id
        name: name
        type_is_crypto: 0
        data_quote_start: 2000-01-23T04:56:07.000+00:00
        data_quote_end: 2000-01-23T04:56:07.000+00:00
        data_orderbook_start: 2000-01-23T04:56:07.000+00:00
        data_orderbook_end: 2000-01-23T04:56:07.000+00:00
        data_trade_start: 2000-01-23T04:56:07.000+00:00
        data_trade_end: 2000-01-23T04:56:07.000+00:00
        data_symbols_count: 6
        volume_1hrs_usd: 1.4658129805029452
        volume_1day_usd: 5.962133916683182
        volume_1mth_usd: 5.637376656633329
        price_usd: 2.3021358869347655
        id_icon: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        supply_current: 7.061401241503109
        supply_total: 9.301444243932576
        supply_max: 3.616076749251911
        chain_addresses:
        - chain_id: chain_id
          network_id: network_id
          address: address
        - chain_id: chain_id
          network_id: network_id
          address: address
        data_start: data_start
        data_end: data_end
      properties:
        asset_id:
          description: Gets or sets the asset ID.
          nullable: true
          type: string
        name:
          description: Gets or sets the name of the asset.
          nullable: true
          type: string
        type_is_crypto:
          description: Gets or sets a value indicating whether the asset is a cryptocurrency.
          format: int32
          type: integer
        data_quote_start:
          description: Gets or sets the start date of quote data.
          format: date-time
          nullable: true
          type: string
        data_quote_end:
          description: Gets or sets the end date of quote data.
          format: date-time
          nullable: true
          type: string
        data_orderbook_start:
          description: Gets or sets the start date of order book data.
          format: date-time
          nullable: true
          type: string
        data_orderbook_end:
          description: Gets or sets the end date of order book data.
          format: date-time
          nullable: true
          type: string
        data_trade_start:
          description: Gets or sets the start date of trade data.
          format: date-time
          nullable: true
          type: string
        data_trade_end:
          description: Gets or sets the end date of trade data.
          format: date-time
          nullable: true
          type: string
        data_symbols_count:
          description: Gets or sets the number of symbols.
          format: int64
          nullable: true
          type: integer
        volume_1hrs_usd:
          description: Gets or sets the USD volume in the last 1 hour.
          format: double
          nullable: true
          type: number
        volume_1day_usd:
          description: Gets or sets the USD volume in the last 1 day.
          format: double
          nullable: true
          type: number
        volume_1mth_usd:
          description: Gets or sets the USD volume in the last 1 month.
          format: double
          nullable: true
          type: number
        price_usd:
          description: Gets or sets the USD price of the asset.
          format: double
          nullable: true
          type: number
        id_icon:
          description: Gets or sets the ID of the icon for the asset.
          format: uuid
          nullable: true
          type: string
        supply_current:
          description: Gets or sets the current supply of the asset.
          format: double
          nullable: true
          type: number
        supply_total:
          description: Gets or sets the total supply of the asset.
          format: double
          nullable: true
          type: number
        supply_max:
          description: Gets or sets the maximum supply of the asset.
          format: double
          nullable: true
          type: number
        chain_addresses:
          description: ""
          items:
            $ref: "#/components/schemas/v1.ExchangeRatesChainNetworkAddress"
          nullable: true
          type: array
        data_start:
          nullable: true
          readOnly: true
          type: string
        data_end:
          nullable: true
          readOnly: true
          type: string
      type: object
    v1.ExchangeRate:
      additionalProperties: false
      description: Represents an exchange rate.
      example:
        time: 2000-01-23T04:56:07.000+00:00
        asset_id_base: asset_id_base
        asset_id_quote: asset_id_quote
        rate: 0.8008281904610115
      properties:
        time:
          description: Gets or sets the time of the exchange rate.
          format: date-time
          type: string
        asset_id_base:
          description: Gets or sets the base asset ID of the exchange rate.
          nullable: true
          type: string
        asset_id_quote:
          description: Gets or sets the quote asset ID of the exchange rate.
          nullable: true
          type: string
        rate:
          description: Gets or sets the exchange rate value.
          format: double
          type: number
      type: object
    v1.ExchangeRates:
      additionalProperties: false
      description: Represents exchange rates for a specific base asset.
      example:
        asset_id_base: asset_id_base
        rates:
        - time: 2000-01-23T04:56:07.000+00:00
          asset_id_quote: asset_id_quote
          rate: 0.8008281904610115
        - time: 2000-01-23T04:56:07.000+00:00
          asset_id_quote: asset_id_quote
          rate: 0.8008281904610115
      properties:
        asset_id_base:
          description: Gets or sets the base asset ID.
          nullable: true
          type: string
        rates:
          description: Gets or sets the list of exchange rates.
          items:
            $ref: "#/components/schemas/v1.ExchangeRatesRate"
          nullable: true
          type: array
      type: object
    v1.ExchangeRatesChainNetworkAddress:
      additionalProperties: false
      description: Contains information about assets' chain network addresses
      example:
        chain_id: chain_id
        network_id: network_id
        address: address
      properties:
        chain_id:
          description: Gets or sets chain id
          nullable: true
          type: string
        network_id:
          description: Gets or sets network id
          nullable: true
          type: string
        address:
          description: Gets or sets chain address
          nullable: true
          type: string
      type: object
    v1.ExchangeRatesRate:
      additionalProperties: false
      description: Represents an exchange rate within a collection of exchange rates.
      example:
        time: 2000-01-23T04:56:07.000+00:00
        asset_id_quote: asset_id_quote
        rate: 0.8008281904610115
      properties:
        time:
          description: Gets or sets the time of the exchange rate.
          format: date-time
          type: string
        asset_id_quote:
          description: Gets or sets the quote asset ID of the exchange rate.
          nullable: true
          type: string
        rate:
          description: Gets or sets the exchange rate value.
          format: double
          type: number
      type: object
    v1.Icon:
      additionalProperties: false
      description: Represents an icon.
      example:
        exchange_id: exchange_id
        asset_id: asset_id
        url: url
      properties:
        exchange_id:
          description: Gets or sets the exchange ID associated with the icon.
          nullable: true
          type: string
        asset_id:
          description: Gets or sets the asset ID associated with the icon.
          nullable: true
          type: string
        url:
          description: Gets or sets the URL of the icon.
          nullable: true
          type: string
      type: object
  securitySchemes:
    APIKey:
      description: API Key is required to access the endpoints
      in: header
      name: Authorization
      type: apiKey
    JWT:
      bearerFormat: JWT
      description: "JWT Authorization header using the Bearer scheme. Example: \"\
        Bearer {token}\""
      scheme: bearer
      type: http

